export interface BudgetLineTemplate {
    description: string
    subcategory: string
    suggestedRate?: number
}

export const BUDGET_PRESETS: Record<string, BudgetLineTemplate[]> = {
    "A": [ // Pre-Production & Wrap
        { description: "Line Producer", subcategory: "crew", suggestedRate: 400 },
        { description: "Production Manager", subcategory: "crew" },
        { description: "Production Coordinator", subcategory: "crew" },
        { description: "Office PA", subcategory: "crew" },
        { description: "PA 2", subcategory: "crew" },
        { description: "PA 3", subcategory: "crew" },
        { description: "VFX Supervisor", subcategory: "crew" },
        { description: "Grip Driver", subcategory: "crew" },
        { description: "Dailies Carrier", subcategory: "crew" },
        { description: "Assistant Director", subcategory: "crew" },
        { description: "2nd Assistant Director", subcategory: "crew" },
        { description: "Security Head", subcategory: "crew" },
        { description: "Security Personnel (8)", subcategory: "crew" },
        { description: "Translator", subcategory: "crew" },
    ],
    "B": [ // Shoot / Production Crew
        { description: "Director of Photography", subcategory: "crew" },
        { description: "Camera Operator", subcategory: "crew" },
        { description: "1st Assistant Camera", subcategory: "crew" },
        { description: "2nd Assistant Camera", subcategory: "crew" },
        { description: "Digital Imaging Tech", subcategory: "crew" },
        { description: "Gaffer", subcategory: "crew" },
        { description: "Best Boy Electric", subcategory: "crew" },
        { description: "Key Grip", subcategory: "crew" },
        { description: "Best Boy Grip", subcategory: "crew" },
        { description: "Sound Mixer", subcategory: "crew" },
        { description: "Boom Operator", subcategory: "crew" },
        { description: "Video Assist", subcategory: "crew" },
        { description: "Stunt Supervisor", subcategory: "crew" },
        { description: "Stunt Performers (4)", subcategory: "crew" },
        { description: "Medic / Fireman", subcategory: "crew" },
        { description: "Craft Service", subcategory: "crew" },
        { description: "Caterers (3)", subcategory: "crew" },
        { description: "Art Swing x 3", subcategory: "crew" },
        { description: "Welfare / Teacher", subcategory: "crew" },
        { description: "2nd Unit Camera", subcategory: "crew" },
        { description: "2nd Unit Dir & 2nd AD", subcategory: "crew" },
        { description: "Meals for Crew & Talent", subcategory: "meals" },
        { description: "Stage Manager Overtime", subcategory: "crew" },
    ],
    "C": [ // Casting
        { description: "Casting Director", subcategory: "casting" },
        { description: "Casting Assistant", subcategory: "casting" },
        { description: "Casting Facilities", subcategory: "casting" },
        { description: "Working Meals", subcategory: "meals" },
        { description: "Call Back Expenses", subcategory: "casting" },
    ],
    "D": [ // Location & Travel
        { description: "Location Fees", subcategory: "fees" },
        { description: "Permits", subcategory: "fees" },
        { description: "Auto Rentals", subcategory: "transportation" },
        { description: "Limousines", subcategory: "transportation" },
        { description: "Trucking", subcategory: "transportation" },
        { description: "Air Fares", subcategory: "travel" },
        { description: "Hotel Accommodations", subcategory: "travel" },
        { description: "Per Diem", subcategory: "travel" },
        { description: "Helicopter", subcategory: "transportation" },
        { description: "Parking Fees", subcategory: "fees" },
    ],
    "E": [ // Props, Wardrobe, Animals
        { description: "Prop Rental", subcategory: "props" },
        { description: "Prop Purchase", subcategory: "props" },
        { description: "Wardrobe Rental", subcategory: "wardrobe" },
        { description: "Wardrobe Purchase", subcategory: "wardrobe" },
        { description: "Wigs & Mustaches", subcategory: "wardrobe" },
        { description: "Animals & Handlers", subcategory: "animals" },
        { description: "Picture Vehicles", subcategory: "vehicles" },
    ],
    "F": [ // Studio & Set Construction
        { description: "Construction Labor", subcategory: "labor" },
        { description: "Scenics", subcategory: "labor" },
        { description: "Construction Materials", subcategory: "materials" },
        { description: "Strike Crew", subcategory: "labor" },
        { description: "Misc Studio Charges", subcategory: "fees" },
        { description: "Power Charge & Bulbs", subcategory: "fees" },
    ],
    "G": [ // Special Effects
        { description: "Special FX Supervisor", subcategory: "labor" },
        { description: "Special FX Asst", subcategory: "labor" },
        { description: "Special FX (Weapons)", subcategory: "labor" },
        { description: "Special FX (Main)", subcategory: "labor" },
        { description: "Pyrotechnics", subcategory: "materials" },
        { description: "Atmosphere (Smoke/Fog)", subcategory: "materials" },
    ],
    "H": [ // Art Department
        { description: "Production Designer", subcategory: "crew" },
        { description: "Art Director", subcategory: "crew" },
        { description: "Set Decorator", subcategory: "crew" },
        { description: "Art Dept Coordinator", subcategory: "crew" },
        { description: "Supplies", subcategory: "materials" },
    ],
    "I": [ // Equipment Rental
        { description: "Camera Rental", subcategory: "camera" },
        { description: "Sound Rental", subcategory: "sound" },
        { description: "Lighting Rental", subcategory: "lighting" },
        { description: "Grip Rental", subcategory: "grip" },
        { description: "Generator Rental", subcategory: "lighting" },
        { description: "Crane / Cherry Picker", subcategory: "grip" },
        { description: "VTR Rental (With Playback)", subcategory: "camera" },
        { description: "VTR Rental (W/O Playback)", subcategory: "camera" },
        { description: "Walkie Talkies / Bull Horns", subcategory: "sound" },
        { description: "Dolly Rental", subcategory: "grip" },
        { description: "Camera Car", subcategory: "vehicles" },
    ],
    "J": [ // Laboratory & Film Stock
        { description: "Purchase Raw Stock", subcategory: "film" },
        { description: "Developing", subcategory: "lab" },
        { description: "Transfer to Mag", subcategory: "lab" },
        { description: "Digital Processing", subcategory: "lab" },
        { description: "Hard Drives", subcategory: "materials" },
    ],
    "K": [ // Miscellaneous & Editorial (from source)
        { description: "Editor", subcategory: "editorial" },
        { description: "Assistant Editor", subcategory: "editorial" },
        { description: "Final Color Correction", subcategory: "finishing" },
        { description: "Sound Design/Mix", subcategory: "audio" },
        { description: "Petty Cash", subcategory: "expenses" },
        { description: "Air Shipping", subcategory: "expenses" },
        { description: "Phones & Cables", subcategory: "expenses" },
        { description: "Special Insurances", subcategory: "insurance" },
    ],
    "L": [ // Director / Creative Fees
        { description: "Director Fee", subcategory: "fees" },
        { description: "Creative Director", subcategory: "fees" },
        { description: "Producer Fee", subcategory: "fees" },
        { description: "Screenwriter Fee", subcategory: "fees" },
    ],
    "M": [ // Insurance
        { description: "General Liability", subcategory: "insurance" },
        { description: "Equipment Insurance", subcategory: "insurance" },
        { description: "Workers Compensation", subcategory: "insurance" },
        { description: "Errors & Omissions", subcategory: "insurance" },
    ],
    "N": [ // Talent
        { description: "O/C Principals", subcategory: "talent" },
        { description: "Extras", subcategory: "talent" },
        { description: "Stunt Doubles", subcategory: "talent" },
        { description: "Fitting Fees", subcategory: "talent" },
        { description: "Payroll Taxes", subcategory: "benefits" },
        { description: "Agency Fees", subcategory: "fees" },
    ]
}
